"""empty message

Revision ID: 8f0646768c3c
Revises: ef859024f39e
Create Date: 2023-10-07 09:57:50.430633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0646768c3c'
down_revision = 'ef859024f39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userextractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_document_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userextractions', schema=None) as batch_op:
        batch_op.drop_column('output_document_name')

    # ### end Alembic commands ###
